#define SECRET_SSID "<YOUR SSID NAME>"
#define SECRET_PASS "<YOUR NETWORK PASSWORD>"
#define SECRET_FALLBACK_SSID "<YOUR SSID NAME>"
#define SECRET_FALLBACK_WIFIPASS "<YOUR NETWORK PASSWORD>"
#define SECRET_MQTT_USER "<YOUR MQTT USERNAME>"
#define SECRET_MQTT_PASS "<YOUR MQTT SERVER PASSWORD>"
#define SECRET_MQTT_IP "<YOUR MQTT SERVER IP>"
#define SECRET_MQTT_PORT <YOUR MQTT SERVER PORT>
